#Enable/Disable Server Entries overrides
enabled = true
#Internal Version Number. NO TOUCHY!
version = 2
#Server override entries
[[entry]]
	ip = "freefantasycraft.ddns.net"
	description = "An official FFC-SMP"
	state = "creating and socializing"
	largeImageKey = ""
	largeImageText = ""
	smallImageKey = ""
	smallImageText = ""

